/*
 * runtime/pokes-db.js — lazy loader + title search over the pokes catalog
 * (static/pokes/pokes.json, generated by tools/gen-pokes-catalog.js from the
 * Tipshop poke database).
 *
 * Matching is by normalised title: catalog names are TOSEC style ("Spy Who
 * Loved Me, The") while loaded-game names come from a filename or URL
 * ("007 - The Spy Who Loved Me"), so we compare article-free token sets and rank
 * by overlap rather than requiring equality.
 */

// Resolved against the jsspeccy script URL. Guarded for Node.
const scriptUrl =
    (typeof document !== 'undefined' && document.currentScript)
        ? document.currentScript.src
        : (typeof import.meta !== 'undefined' ? import.meta.url : '');

const POKES_URL = 'pokes/pokes.json';

const ARTICLES = new Set(['the', 'a', 'an']);

// Lowercase, strip a file extension and bracketed junk, keep only
// alphanumerics, drop articles ("Game, The" / "The Game" / "007 - The Game"
// all reduce to the same tokens).
export function titleTokens(title) {
    const cleaned = (title || '')
        .toLowerCase()
        .replace(/\.(tap|tzx|z80|sna|szx|zip)$/, '')
        .replace(/\([^)]*\)/g, ' ')
        .replace(/\[[^\]]*\]/g, ' ')
        .replace(/[^a-z0-9]+/g, ' ')
        .trim();
    return cleaned.split(' ').filter(t => t && !ARTICLES.has(t));
}

export class PokesDatabase {
    constructor() {
        this._loadPromise = null;
        this.games = null;   // [{name, year, pub, tokens, trainers}]
    }

    load() {
        if (!this._loadPromise) this._loadPromise = this._doLoad();
        return this._loadPromise;
    }

    async _doLoad() {
        const url = new URL(POKES_URL, scriptUrl).href;
        const resp = await fetch(url);
        if (!resp.ok) throw new Error('HTTP ' + resp.status);
        const catalog = await resp.json();
        this.games = catalog.games.map(([name, year, pub, trainers], id) => ({
            id,
            name,
            year,
            pub,
            tokens: titleTokens(name),
            trainers: trainers.map(([tname, pokes]) => ({
                name: tname,
                pokes: pokes.map(([bank, address, value, original]) =>
                    ({ bank, address, value, original })),
            })),
        }));
        return this;
    }

    /* Rank games against a free-text query. Returns up to `limit` matches,
     * best first. Score: 3 = same token set, 2 = one set contains the other,
     * else the fraction of query tokens present in the title (> 0.5 required
     * so short queries don't match everything). */
    search(query, limit) {
        limit = limit || 40;
        const qTokens = titleTokens(query);
        if (!qTokens.length || !this.games) return [];
        const qSet = new Set(qTokens);
        const scored = [];
        for (const game of this.games) {
            const gSet = new Set(game.tokens);
            let common = 0;
            for (const t of qSet) if (gSet.has(t)) common++;
            let score;
            if (common === qSet.size && common === gSet.size) score = 3;
            else if (common === gSet.size || common === qSet.size) score = 2;
            else score = common / qSet.size;
            if (score > 0.5) scored.push({ game, score });
        }
        scored.sort((a, b) =>
            (b.score - a.score) || a.game.name.localeCompare(b.game.name));
        return scored.slice(0, limit).map(s => s.game);
    }
}

export default PokesDatabase;
